#Database connection
#Plugin will automatically create table Whitelist
host: localhost
port: 3306
user: root
password: ''
db: minecraft

#Kick message, if not whitelisted
kick: "Please register at http://myweb.org"